---
- hosts: "{{ terraform_group | default('None')}}"
  tasks:
   - name: env
     shell: env
   - name: Create infra with terraform
     terraform:
       project_path: project/
       state: present
       force_init: "{{ force_init | default('False')}}"
       backend_config:
          resource_group_name: "asdfasdfsss"
          storage_account_name: "RG_prd_CC_abc_abc"
          container_name: "tfstate"
          key: "teste.terraform.tfstate"
- hosts: "{{ arm_group | default('None')}}"
  tasks: 
   - name: ping
     ping: 
