---
- hosts: "{{ terraform_group | default('None')}}"
  tasks: 
   - name: Create infra with terraform
     terraform:
       project_path: project/
       state: present
       force_init: "{{ force_init | default('False')}}"
       backend_config:
          resource_group_name: "cloud-shell-storage-eastus"
          storage_account_name: "rgprdccabcabcdiag"
          container_name: "tfstate"
          key: "teste.terraform.tfstate"
- hosts: "{{ arm_group | default('None')}}"
  tasks: 
   - name: ping
     ping: 
