---
- hosts: "{{ terraform_group | default('None')}}"
  vars: 
   variable_object: []
  tasks:

   - name: Create infra with terraform
     terraform:
       project_path: "{{ project_path }}"
#      project_path: projects/project_1/
       state: "{{project_state| default('present')}}"
       force_init: "{{ force_init | default('False')}}"
#      variables: "{{ variable_object }}"
       workspace: "{{ workspace_name }}"
       backend_config:
          resource_group_name: "asdfasdfsss"
          storage_account_name: "RG_prd_CC_abc_abc"
          container_name: "tfstate"
          key: "teste.terraform.tfstate"
- hosts: "{{ arm_group | default('None')}}"
  tasks: 
   - name: ping
     ping: 
